version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    environment:
      - NODE_ENV=production
      - PORT=9000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:9000']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
